# Generated by Django 2.2.7 on 2019-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Lastname')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
            ],
        ),
    ]
