# Generated by Django 2.2.7 on 2019-12-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
    ]
